
services:
  ris-server:
    build: ./ris
    container_name: ris-netconf-server
    ports:
      - "830:830"
    networks:
      - netconf-net

  netconf-controller:
    build: ./controller
    container_name: controller-netconf-client
    depends_on:
      - ris-server
    networks:
      - netconf-net
    tty: true
    stdin_open: true

networks:
  netconf-net:
    driver: bridge
